## NUMPY 

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
arr.dtype

dtype('int32')

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.randn(5)

array([-0.08656078,  0.33776401,  1.61927193,  1.33541716, -0.04550356])

In [36]:
np.random.randn(5,5)

array([[-0.64583128,  0.96634276, -0.37728403,  0.38288682, -1.39438272],
       [-0.31745706, -0.80035063, -1.98894645, -2.0512259 , -0.92262628],
       [-0.63552997, -1.4501135 ,  0.99217268, -0.18694268,  0.04579427],
       [ 0.44499074, -0.3660006 ,  0.13038789,  2.08317221, -0.40451172],
       [ 0.46947837, -1.0378897 , -1.13557119, -0.10503047, -0.09890114]])

In [40]:
np.random.randn(4,4)

array([[-2.5180373 ,  1.82247291, -0.39749313,  0.90297456],
       [ 0.74567354,  0.73106915, -0.17634038,  0.96971643],
       [-1.19408004, -0.03753831, -0.7618677 , -1.51282838],
       [-2.67354914,  0.9363905 , -0.67265495,  1.6216751 ]])

In [45]:
np.random.randint(1,100,10)

array([52, 23, 55, 41, 95, 97, 60, 92,  8, 78])

In [46]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr = np.random.randint(0,50,10)
ranarr

array([17, 14, 17, 23, 31, 28, 29, 26, 28, 23])

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr_1 = np.arange(24)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
arr_1.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [57]:
arr_1.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [64]:
arr_1.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [65]:
arr_1.max()

23

In [66]:
ranarr.max()

31

In [67]:
ranarr.min()

14

In [68]:
ranarr

array([17, 14, 17, 23, 31, 28, 29, 26, 28, 23])

In [70]:
ranarr.argmin()

1

In [71]:
ranarr.shape

(10,)

In [74]:
arr.shape

(25,)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr.reshape(5,5).shape

(5, 5)

In [77]:
arr.dtype

dtype('int32')

## Numpy indexing and selection 

In [81]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[8]

8

In [87]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [133]:
arr[::-3]

array([10,  7,  4,  1])

In [138]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [137]:
arr_2d.ndim

2

In [140]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [148]:
arr_2d[1,2]

30

In [150]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [152]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
bool_arr = arr > 5 
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [156]:
arr[arr < 3]

array([0, 1, 2])

In [158]:
arr_2d_1 = np.arange(50).reshape(5,10)
arr_2d_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [166]:
arr_2d_1[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [167]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [168]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [169]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [170]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [171]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [172]:
arr / arr

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_7740\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [173]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [174]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [175]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [178]:
np.max(arr)

10

In [179]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [180]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [182]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [183]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [186]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [187]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [190]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [197]:
np.random.rand(1)

array([0.83899307])

In [198]:
np.random.randn(25)

array([ 0.44491983, -1.88872555,  0.22658717, -1.20564293, -1.44776537,
       -0.29552608,  0.79041423,  0.81732002,  1.12153785, -0.48599119,
        0.76375403,  1.47532559,  0.45461178, -0.53940185,  0.45962344,
       -0.22303123,  0.85912425, -0.41746323,  1.53412272,  0.44088356,
        0.4232507 , -1.47996001,  2.05333744,  0.33978282, -0.26962599])

In [199]:
np.random.randn(25).shape

(25,)

In [206]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [207]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [208]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [210]:
mat[3,4]

20

In [211]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [216]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [217]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [218]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [219]:
mat.sum()

325

In [221]:
mat.std()

7.211102550927978

In [222]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [224]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## sample practice 

In [225]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
a < 4

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [230]:
print(a %2 == 0)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [235]:
np.count_nonzero(a < 10)

10

In [236]:
np.count_nonzero(a%2 == 1)

6

In [237]:
np.sum(a < 4)

4